// Code generated by protoc-gen-go. DO NOT EDIT.
// source: myservice.proto

package myservicepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddDataRequest struct {
	ServerIp             string            `protobuf:"bytes,1,opt,name=server_ip,json=serverIp,proto3" json:"server_ip,omitempty"`
	ClientIp             string            `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Msg                  string            `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AddDataRequest) Reset()         { *m = AddDataRequest{} }
func (m *AddDataRequest) String() string { return proto.CompactTextString(m) }
func (*AddDataRequest) ProtoMessage()    {}
func (*AddDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_myservice_90031cc0239956c8, []int{0}
}
func (m *AddDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDataRequest.Unmarshal(m, b)
}
func (m *AddDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDataRequest.Marshal(b, m, deterministic)
}
func (dst *AddDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDataRequest.Merge(dst, src)
}
func (m *AddDataRequest) XXX_Size() int {
	return xxx_messageInfo_AddDataRequest.Size(m)
}
func (m *AddDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddDataRequest proto.InternalMessageInfo

func (m *AddDataRequest) GetServerIp() string {
	if m != nil {
		return m.ServerIp
	}
	return ""
}

func (m *AddDataRequest) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *AddDataRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *AddDataRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*AddDataRequest)(nil), "myservicepb.AddDataRequest")
	proto.RegisterMapType((map[string]string)(nil), "myservicepb.AddDataRequest.MetadataEntry")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MyServiceClient is the client API for MyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MyServiceClient interface {
	AddData(ctx context.Context, in *AddDataRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type myServiceClient struct {
	cc *grpc.ClientConn
}

func NewMyServiceClient(cc *grpc.ClientConn) MyServiceClient {
	return &myServiceClient{cc}
}

func (c *myServiceClient) AddData(ctx context.Context, in *AddDataRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/myservicepb.MyService/AddData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyServiceServer is the server API for MyService service.
type MyServiceServer interface {
	AddData(context.Context, *AddDataRequest) (*empty.Empty, error)
}

func RegisterMyServiceServer(s *grpc.Server, srv MyServiceServer) {
	s.RegisterService(&_MyService_serviceDesc, srv)
}

func _MyService_AddData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).AddData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myservicepb.MyService/AddData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).AddData(ctx, req.(*AddDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "myservicepb.MyService",
	HandlerType: (*MyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddData",
			Handler:    _MyService_AddData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "myservice.proto",
}

func init() { proto.RegisterFile("myservice.proto", fileDescriptor_myservice_90031cc0239956c8) }

var fileDescriptor_myservice_90031cc0239956c8 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0xad, 0x2c, 0x4e,
	0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x86, 0x0b, 0x14,
	0x24, 0x49, 0x49, 0xa7, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x83, 0xa5, 0x92, 0x4a, 0xd3, 0xf4,
	0x53, 0x73, 0x0b, 0x4a, 0x2a, 0x21, 0x2a, 0x95, 0x1e, 0x30, 0x72, 0xf1, 0x39, 0xa6, 0xa4, 0xb8,
	0x24, 0x96, 0x24, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x49, 0x73, 0x71, 0x82, 0x34,
	0xa7, 0x16, 0xc5, 0x67, 0x16, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x71, 0x40, 0x04, 0x3c,
	0x0b, 0x40, 0x92, 0xc9, 0x39, 0x99, 0xa9, 0x79, 0x25, 0x20, 0x49, 0x26, 0x88, 0x24, 0x44, 0xc0,
	0xb3, 0x40, 0xc8, 0x95, 0x8b, 0x23, 0x37, 0xb5, 0x24, 0x31, 0x25, 0xb1, 0x24, 0x51, 0x82, 0x59,
	0x81, 0x59, 0x83, 0xdb, 0x48, 0x53, 0x0f, 0xc9, 0x25, 0x7a, 0xa8, 0x16, 0xe9, 0xf9, 0x42, 0xd5,
	0xba, 0xe6, 0x95, 0x14, 0x55, 0x06, 0xc1, 0xb5, 0x0a, 0x09, 0x70, 0x31, 0xe7, 0x16, 0xa7, 0x4b,
	0xb0, 0x80, 0x4d, 0x07, 0x31, 0xa5, 0xac, 0xb9, 0x78, 0x51, 0x14, 0x83, 0x94, 0x64, 0xa7, 0x56,
	0x42, 0x5d, 0x07, 0x62, 0x0a, 0x89, 0x70, 0xb1, 0x96, 0x25, 0xe6, 0x94, 0xa6, 0x42, 0x1d, 0x05,
	0xe1, 0x58, 0x31, 0x59, 0x30, 0x1a, 0xf9, 0x72, 0x71, 0xfa, 0x56, 0x06, 0x43, 0x1c, 0x21, 0xe4,
	0xc0, 0xc5, 0x0e, 0x75, 0x85, 0x90, 0x34, 0x1e, 0xb7, 0x49, 0x89, 0xe9, 0x41, 0x42, 0x4d, 0x0f,
	0x16, 0x6a, 0x7a, 0xae, 0xa0, 0x50, 0x53, 0x62, 0x48, 0x62, 0x03, 0x8b, 0x18, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x60, 0x07, 0xe6, 0x96, 0x75, 0x01, 0x00, 0x00,
}
